id: ACF432440
base_file: fFF66.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:06:02.438258
  last_modified_at: 2022-06-05 20:06:02.438284
